# Release: https://github.com/azaidelson/excalidraw/releases/tag/v4.1.0
# Workflow URL: https://github.com/azaidelson/excalidraw/actions/runs/15619879963
# Commit: https://github.com/azaidelson/excalidraw/commit/a62e79fa9e7f37c82f9d6160b86083f266d6fbb1
version: '3'
services:
  app:
    image: ghcr.io/azaidelson/excalidraw@sha256:b4d1472c63f41f1d74da737e67c1ec4f524772ff2e1f6fdd2ba3ac7f03554712
    ports:
      - '3000:80'
