# Release: https://github.com/azaidelson/excalidraw/releases/tag/v4.0.7
# Workflow URL: https://github.com/azaidelson/excalidraw/actions/runs/15570105096
# Commit: https://github.com/azaidelson/excalidraw/commit/03bc84598582a9d824a2345ba912b8128fbf67cb
version: '3'
services:
  app:
    image: ghcr.io/azaidelson/excalidraw@sha256:c0a0aa1a7d5274d8169b350724f5f9c3d3302cf0a00f669d64efbabeceb2bfaf
    ports:
      - '3000:80'
