# Release: https://github.com/azaidelson/excalidraw/releases/tag/v2.3.4
# Workflow URL: https://github.com/azaidelson/excalidraw/actions/runs/16964647758
# Commit: https://github.com/azaidelson/excalidraw/commit/fae832f1f79df99fc612f8f2d2748477d697e7a5
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/azaidelson/excalidraw@sha256:30692217d03c65d72855c3fc013d4220ee7c0596dd8d32a5598f877e1d35f4fa
    ports:
      - '8080'
